package com.petbuddy.petbuddystore.common.exception;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "Uncategorized error", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(9998, "Uncategorized error", HttpStatus.BAD_REQUEST),

    EMAIL_REQUIRED(1002, "Email is required", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(1003, "Email is invalid", HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID(1004, "Password must be at least 8 characters", HttpStatus.BAD_REQUEST),
    FULL_NAME_REQUIRED(1005, "Full name is required", HttpStatus.BAD_REQUEST),
    GENDER_REQUIRED(1006, "Gender is required", HttpStatus.BAD_REQUEST),
    DATE_OF_BIRTH_REQUIRED(1007, "Date of birth is required", HttpStatus.BAD_REQUEST),
    EMAIL_EXISTED(1008, "User with this email already exists", HttpStatus.BAD_REQUEST),
    USER_NOT_EXISTED(1009, "User does not exists", HttpStatus.NOT_FOUND),
    INVALID_DOB_FORMAT(1010, "Date of birth must be in format dd-MM-yyyy", HttpStatus.BAD_REQUEST),

    USER_NOT_VERIFIED(2001, "Please verify your email before logging in", HttpStatus.FORBIDDEN),
    USER_INACTIVE(2002, "User is inactive", HttpStatus.FORBIDDEN),
    USER_SUSPENDED(2003, "User has been suspended", HttpStatus.FORBIDDEN),
    USER_DELETED(2004, "User has been deleted", HttpStatus.GONE),
    UNAUTHENTICATED(2005, "Unauthenticated", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(2006, "You do not have permission to access", HttpStatus.FORBIDDEN),
    INVALID_TOKEN(2007, "Invalid token", HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(2008, "Token has expired", HttpStatus.UNAUTHORIZED),
    USER_NOT_FOUND(2009, "User not found", HttpStatus.NOT_FOUND),

    MESSAGE_EXCEED_LIMIT(2101, "Message must be less than 2000 characters", HttpStatus.BAD_REQUEST),

    OTP_EXPIRED(3001, "OTP has expired", HttpStatus.BAD_REQUEST),
    OTP_INVALID(3002, "OTP is invalid", HttpStatus.BAD_REQUEST),
    OTP_MAX_ATTEMPT(3003, "Too many attempts. Try again later", HttpStatus.BAD_REQUEST),
    OTP_RESEND_COOLDOWN(3004, "Please wait before requesting another OTP", HttpStatus.BAD_REQUEST),
    OTP_RATE_LIMIT(3005, "Too many OTP requests", HttpStatus.BAD_REQUEST),
    EMAIL_SEND_FAILED(3006, "Failed to send email", HttpStatus.INTERNAL_SERVER_ERROR),
    EMAIL_ALREADY_VERIFIED(3007, "Email has already verified", HttpStatus.BAD_REQUEST),
    OTP_REQUIRED(3008, "Otp is required", HttpStatus.BAD_REQUEST),
    PASSWORD_INCORRECT(3009, "Old password is incorrect", HttpStatus.BAD_REQUEST),
    PASSWORD_CONFIRM_NOT_MATCH(3010, "Password confirmation does not match", HttpStatus.BAD_REQUEST),
    PASSWORD_SAME_AS_OLD(3011, "New password must be different from old password", HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(3012, "Password is required", HttpStatus.BAD_REQUEST),

    CATEGORY_NAME_REQUIRED(4101, "Category name is required", HttpStatus.BAD_REQUEST),
    CATEGORY_EXISTED(4102, "Category already exists", HttpStatus.BAD_REQUEST),
    CATEGORY_NOT_FOUND(4103, "Category not found", HttpStatus.NOT_FOUND),
    CATEGORY_HAS_PRODUCTS(4104, "Cannot delete category because it is linked to products", HttpStatus.BAD_REQUEST),
    CATEGORY_DELETED(4105, "Category has been deleted", HttpStatus.BAD_REQUEST),
    CATEGORY_REQUIRED(4108, "Category is required", HttpStatus.BAD_REQUEST),


    PRODUCT_STOCK_INVALID(4205, "Product stock quantity must be greater than or equal to 1", HttpStatus.BAD_REQUEST),
    PRODUCT_EXISTED(4206, "Product already exists", HttpStatus.BAD_REQUEST),
    PRODUCT_NOT_FOUND(4207, "Product not found", HttpStatus.NOT_FOUND),
    PRODUCT_DELETED(4208, "Product has been deleted", HttpStatus.BAD_REQUEST),
    PRODUCT_NOT_DELETED(4209, "Product is not deleted", HttpStatus.BAD_REQUEST),
    CATEGORY_ID_REQUIRED(4210, "Category id is required", HttpStatus.BAD_REQUEST),
    PRODUCT_STATUS_REQUIRED(4211, "Product status is required", HttpStatus.BAD_REQUEST),
    PRODUCT_IMAGE_REQUIRED(4212, "Product image is required", HttpStatus.BAD_REQUEST),
    EXPIRY_DATE_REQUIRED(4213, "Expiry date is required", HttpStatus.BAD_REQUEST),
    EXPIRY_DATE_INVALID(4214, "Expiry date must be in the future", HttpStatus.BAD_REQUEST),
    PRODUCT_OUT_OF_STOCK(4215, "Product out of stock", HttpStatus.BAD_REQUEST),
    INVALID_SORT_OPTION(4216, "Invalid sort option", HttpStatus.BAD_REQUEST),
    PRODUCT_IMAGE_LIMIT_EXCEEDED(4217, "Cannot upload more than 4 images for a product", HttpStatus.BAD_REQUEST),
    BATCH_REQUIRED(4218, "Batch list is required", HttpStatus.BAD_REQUEST),
    BATCH_LIMIT_EXCEEDED(4219, "Cannot create more than 10 batches at once", HttpStatus.BAD_REQUEST),
    BATCH_NOT_FOUND(4220, "Batch not found", HttpStatus.NOT_FOUND),
    PRODUCT_HAS_BATCHES(4221, "Cannot delete product because it has batches", HttpStatus.BAD_REQUEST),
    PRODUCT_INACTIVE(4222, "Product is inactive", HttpStatus.BAD_REQUEST),
    PRODUCT_PRICE_CHANGE(4223, "Product price has changed", HttpStatus.BAD_REQUEST),
    PRODUCT_HAS_ACTIVE_PROMOTION(4224,"Sản phẩm đang có chương trình khuyến mãi đang hoạt động",HttpStatus.BAD_REQUEST),
    PRODUCT_PRICE_INVALID(4225, "Product price must be greater than 0", HttpStatus.BAD_REQUEST),
    PRODUCT_NAME_REQUIRED(4226, "Product name is required", HttpStatus.BAD_REQUEST),
    PRODUCT_NAME_INVALID(4227, "Product name must not exceed 255 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_DESCRIPTION_INVALID(4228, "Product description must not exceed 2000 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_INGREDIENTS_INVALID(4229, "Product ingredients must not exceed 1000 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_USAGE_INSTRUCTIONS_INVALID(4230, "Product usage instructions must not exceed 1000 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_PRICE_REQUIRED(4231, "Product price is required", HttpStatus.BAD_REQUEST),
    PRODUCT_UNIT_REQUIRED(4232, "Product unit is required", HttpStatus.BAD_REQUEST),
    PRODUCT_BRAND_REQUIRED(4233, "Product brand is required", HttpStatus.BAD_REQUEST),
    PRODUCT_BRAND_INVALID(4234, "Product brand must not exceed 255 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_REASON_INVALID(4235, "Product reason must not exceed 500 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_NOTE_INVALID(4236, "Product note must not exceed 1000 characters", HttpStatus.BAD_REQUEST),
    PRODUCT_STOCK_REQUIRED(4240, "Product stock quantity is required", HttpStatus.BAD_REQUEST),
    BASE_PRICE_REQUIRED(4241, "Base price is required", HttpStatus.BAD_REQUEST),
    BASE_PRICE_FORMAT_INVALID(4242, "Base price must be a valid number with up to 2 decimal places", HttpStatus.BAD_REQUEST),
    BASE_PRICE_INVALID(4243, "Base price must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
    BATCH_REASON_INVALID(4244, "Batch reason must not exceed 500 characters", HttpStatus.BAD_REQUEST),
    BATCH_NOTE_INVALID(4245, "Batch note must not exceed 1000 characters", HttpStatus.BAD_REQUEST),
    BATCH_EXPIRY_DATE_INVALID(4246, "Expiry date must be in the future", HttpStatus.BAD_REQUEST),
    BASE_PRICE_GREATER_THAN_SALE_PRICE(4247, "Base price cannot be greater than sale price", HttpStatus.BAD_REQUEST),
    SALE_PRICE_LESS_THAN_BASE_PRICE(4248,"Sale price must be greater than base price",HttpStatus.BAD_REQUEST),
    PRODUCT_DISCONTINUED(4249,"Sản phẩm đã ngừng kinh doanh, vui lòng tạo đơn hoàn tiền",HttpStatus.BAD_REQUEST),
    OUT_OF_STOCK(4250,"sản phẩm hết hàng",HttpStatus.BAD_REQUEST),
    RESTOCK_QUANTITY_EXCEEDED(4251, "Số lượng nhập kho vượt quá số lượng yêu cầu hoàn trả", HttpStatus.BAD_REQUEST),
    RESTOCK_QUANTITY_REQUIRED(4252, "Vui lòng nhập số lượng cho ít nhất 1 batch", HttpStatus.BAD_REQUEST),
    RESTOCK_BATCH_NOT_FOUND(4253, "Không tìm thấy batch được chọn để nhập kho", HttpStatus.BAD_REQUEST),
    RESTOCK_INVALID_REQUEST(4254, "Yêu cầu nhập kho không hợp lệ", HttpStatus.BAD_REQUEST),
    RESERVED_STOCK_NOT_FOUND(4255, "Không tìm thấy thông tin giữ hàng", HttpStatus.BAD_REQUEST),
    RESERVED_STOCK_EXPIRED(4256, "Thời gian giữ hàng đã hết hạn", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST(4257, "Yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    RESTOCK_ONLY_AFTER_COMPLETED(4260, "Chỉ có thể nhập kho sau khi đơn đã hoàn tiền (COMPLETED)", HttpStatus.BAD_REQUEST),
    ALREADY_RESTOCKED(4261, "Đơn hàng đã được nhập kho trước đó", HttpStatus.BAD_REQUEST),

    REVIEW_NOT_FOUND(4300, "Review not found", HttpStatus.NOT_FOUND),
    REVIEW_ALREADY_EXISTS(4301, "You have already reviewed this product", HttpStatus.CONFLICT),
    REVIEW_DAILY_LIMIT_EXCEEDED(4302, "Daily review limit exceeded (max 10 reviews per day)", HttpStatus.TOO_MANY_REQUESTS),
    UNAUTHORIZED_REVIEW_ACCESS(4303, "You are not authorized to access this review", HttpStatus.FORBIDDEN),
    RATING_INVALID(4304, "Rating must be between 1 and 5", HttpStatus.BAD_REQUEST),
    INVALID_CONTENT(4305, "Content is required", HttpStatus.BAD_REQUEST),
    CONTENT_TOO_LONG(4306, "Content must not exceed 1000 characters", HttpStatus.BAD_REQUEST),
    REVIEW_ALREADY_DELETED(4307, "Review has been deleted", HttpStatus.BAD_REQUEST),
    REVIEW_NOT_ACTIVE(4308, "Review is not active", HttpStatus.BAD_REQUEST),
    RATING_REQUIRED(4309, "Rating is required", HttpStatus.BAD_REQUEST),
    CONTENT_REQUIRED(4310, "Content is required", HttpStatus.BAD_REQUEST),

    CART_EMPTY(5101, "Cart is empty", HttpStatus.BAD_REQUEST),
    CART_ITEM_NOT_FOUND(5102, "Cart item not found", HttpStatus.NOT_FOUND),
    INVALID_QUANTITY(5103, "Quantity must be greater than 0", HttpStatus.BAD_REQUEST),

    ORDER_NOT_FOUND(5201, "Order not found", HttpStatus.NOT_FOUND),
    INVALID_ORDER_STATUS(5202, "Invalid order status", HttpStatus.BAD_REQUEST),
    PICKING_LIST_NOT_FOUND(5203, "Picking list not found",HttpStatus.NOT_FOUND),
    PICKING_ALREADY_CREATED(5204, "Picking list already created", HttpStatus.BAD_REQUEST),
    INSUFFICIENT_STOCK(5205, "Insufficient stock",HttpStatus.BAD_REQUEST),
    ORDER_CANCELLED(5206, "Order is cancelled", HttpStatus.CONFLICT),
    ORDER_ALREADY_PAID(5207, "Order is already paid", HttpStatus.CONFLICT),
    ORDER_CANNOT_BE_UPDATED(5208, "Order cannot be updated", HttpStatus.BAD_REQUEST),
    DELIVERY_PROOF_IMAGE_REQUIRED(5209, "Delivery proof image is required", HttpStatus.BAD_REQUEST),
    NOT_SHIPPER(5210, "You are not the shipper of this order", HttpStatus.FORBIDDEN),
    SHIPPER_NOT_ON_DUTY(5211, "Shipper is not on duty", HttpStatus.FORBIDDEN),
    NOT_THE_ASSIGNED_SHIPPER(5212, "You are not the assigned shipper for this order", HttpStatus.FORBIDDEN),
    CANCELLED_NOT_ALLOWED(5513,"Không thể hủy yêu cầu khi đang trong quá trình vận chuyển", HttpStatus.BAD_REQUEST),
    SHIPPER_TOO_FAR_FROM_CLUSTER(5214,"The distance between orders are too far",HttpStatus.FORBIDDEN),
    ROUTE_CALCULATION_FAILED(5215,"Failed to calculate route",HttpStatus.INTERNAL_SERVER_ERROR),
    SHIPPER_CAPACITY_FULL(5216, "Shipper capacity is full", HttpStatus.BAD_REQUEST),

    VOUCHER_NOT_FOUND(5301, "Voucher not found", HttpStatus.NOT_FOUND),
    VOUCHER_CODE_EXISTED(5302, "Voucher code already exists", HttpStatus.BAD_REQUEST),
    VOUCHER_INVALID_DATE(5303, "Voucher date is invalid", HttpStatus.BAD_REQUEST),
    VOUCHER_EXPIRED(5304, "Voucher has expired",HttpStatus.BAD_REQUEST),
    VOUCHER_NOT_STARTED(5305, "Voucher is not active yet",HttpStatus.BAD_REQUEST),
    VOUCHER_OUT_OF_USAGE(5306, "Voucher usage limit exceeded",HttpStatus.BAD_REQUEST),
    VOUCHER_MIN_ORDER_NOT_MET(5307, "Order value does not meet voucher requirement",HttpStatus.BAD_REQUEST),
    VOUCHER_USER_LIMIT_EXCEEDED(5308, "You have reached voucher usage limit",HttpStatus.BAD_REQUEST),
    VOUCHER_INVALID_STATUS(5309, "Voucher is inactive",HttpStatus.BAD_REQUEST),

    LOCATION_OUTSIDE_HCM(5401,"Location is outside Ho Chi Minh city",HttpStatus.BAD_REQUEST),
    INVALID_COORDINATES(5402,"Invalid coordinates",HttpStatus.BAD_REQUEST),
    INVALID_DISTANCE(5403,"Invalid distance",HttpStatus.BAD_REQUEST),
    SHIPPING_CONFIG_NOT_FOUND(5404,"Shipping configuration not found",HttpStatus.NOT_FOUND),
    SHIPPING_RULE_OVERLAP(5405,"Shipping rule overlaps with existing rules",HttpStatus.BAD_REQUEST),
    INVALID_SHIPPING_FEE(5406,"Invalid shipping fee",HttpStatus.BAD_REQUEST),
    LOCATION_ON_WATER(5407,"Location is on water",HttpStatus.BAD_REQUEST),
    STORE_LOCATION_NOT_FOUND(5408,"Store location not found",HttpStatus.NOT_FOUND),

    PAYMENT_NOT_FOUND(5501, "Payment not found", HttpStatus.NOT_FOUND),
    PAYMENT_ALREADY_EXISTS(5502, "Payment already exists", HttpStatus.CONFLICT),
    PAYMENT_INVALID_METHOD(5503, "Invalid payment", HttpStatus.BAD_REQUEST),
    PAYMENT_STRIPE_ERROR(5504, "Payment stripe error", HttpStatus.BAD_GATEWAY),
    PAYMENT_WEBHOOK_INVALID(5505, "Webhook signature invalid", HttpStatus.BAD_REQUEST),
    PAYMENT_INTENT_NOT_FOUND(5506, "PaymentIntent not found", HttpStatus.NOT_FOUND),
    PAYMENT_CANNOT_CANCEL(5507, "Payment can not cancelled", HttpStatus.CONFLICT),
    PAYMENT_NOT_COMPLETED(5508, "Payment is not completed", HttpStatus.BAD_REQUEST),
    PAYMENT_ALREADY_PAID(5509, "Payment is already paid", HttpStatus.BAD_REQUEST),
    PAYMENT_REFUND_NOT_ALLOWED(5510,"Payment refund is not allowed",HttpStatus.BAD_REQUEST),
    PAYMENT_REFUND_FAILED(5511,"Payment refund failed",HttpStatus.INTERNAL_SERVER_ERROR),
    REFUND_NOT_SUPPORTED(5512,"Phương thức thanh toán không hỗ trợ hoàn tiền", HttpStatus.BAD_REQUEST),
    PAYMENT_NOT_PAID(5513,"Đơn hàng chưa được thanh toán", HttpStatus.BAD_REQUEST),
    STRIPE_REFUND_FAILED(5514,"Hoàn tiền qua Stripe thất bại, vui lòng thử lại", HttpStatus.BAD_REQUEST),
    REFUND_METHOD_NOT_SUPPORTED(5515,"Phương thức hoàn tiền không được hỗ trợ", HttpStatus.BAD_REQUEST),
    NO_REMAINING_AMOUNT_TO_REFUND(5516,"Không còn số tiền nào để hoàn trả", HttpStatus.BAD_REQUEST),
    REFUND_AMOUNT_EXCEEDS_REMAINING(5517,"Số tiền hoàn trả vượt quá số tiền còn lại", HttpStatus.BAD_REQUEST),


    PROMOTION_NOT_FOUND(5601, "Promotion not found", HttpStatus.NOT_FOUND),
    PROMOTION_INVALID_DATE(5602, "Promotion date is invalid", HttpStatus.BAD_REQUEST),
    PROMOTION_DISCOUNT_INVALID(5603, "Discount value is invalid", HttpStatus.BAD_REQUEST),
    PROMOTION_START_DATE_MUST_BE_FUTURE(5604, "Ngày bắt đầu khuyến mãi phải là ngày trong tương lai", HttpStatus.BAD_REQUEST),
    PROMOTION_END_DATE_MUST_BE_AFTER_START_DATE(5605, "Ngày kết thúc phải sau ngày bắt đầu", HttpStatus.BAD_REQUEST),
    PROMOTION_NAME_REQUIRED(5606, "Tên khuyến mãi là bắt buộc", HttpStatus.BAD_REQUEST),
    PROMOTION_START_DATE_REQUIRED(5607, "Ngày bắt đầu khuyến mãi là bắt buộc", HttpStatus.BAD_REQUEST),
    PROMOTION_END_DATE_REQUIRED(5608, "Ngày kết thúc khuyến mãi là bắt buộc", HttpStatus.BAD_REQUEST),
    PROMOTION_NOTE_TOO_LONG(5609, "Ghi chú không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    PROMOTION_REASON_TOO_LONG(5610, "Lý do không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),

    AUDIT_LOG_NOT_FOUND(6001, "Audit log not found", HttpStatus.NOT_FOUND),

    FILE_REQUIRED(7001, "File is required", HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(7002, "File size is too large", HttpStatus.BAD_REQUEST),
    INVALID_FILE_TYPE(7003, "Only JPG, PNG, WEBP images are allowed", HttpStatus.BAD_REQUEST),
    UPLOAD_FAILED(7004, "Failed to upload file", HttpStatus.INTERNAL_SERVER_ERROR),
    IMAGE_SIZE_INVALID(7005, "Upload maximum 3 photos", HttpStatus.BAD_REQUEST),
    DELETE_FILE_FAILED(7006, "Failed to delete file", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_EMPTY(7007, "File is empty", HttpStatus.BAD_REQUEST),
    IMPORT_FAILED(7008, "Failed to import file. Please check the file format and data.", HttpStatus.BAD_REQUEST),
    INVALID_EXCEL_TEMPLATE(7009, "Invalid Excel template. Please use the provided template.", HttpStatus.BAD_REQUEST),
    MINIMUM_1_IMAGE_REQUIRED(7010, "At least 1 image is required", HttpStatus.BAD_REQUEST),
    MAXIMUM_5_IMAGES_ALLOWED(7011, "Maximum 5 images are allowed", HttpStatus.BAD_REQUEST),
    RETURN_REQUEST_NOT_FOUND(7012, "Return request not found", HttpStatus.NOT_FOUND),
    RETURN_REQUEST_NOT_PENDING(7013, "Return request is not in pending status", HttpStatus.BAD_REQUEST),
    RETURN_REQUEST_ALREADY_PROCESSED(7015, "Return request has already been processed", HttpStatus.BAD_REQUEST),
    RETURN_QUANTITY_INVALID(7016, "Quantity must be greater than 0", HttpStatus.BAD_REQUEST),
    RETURN_QUANTITY_EXCEEDED(7017, "Quantity exceeds purchased quantity minus already returned quantity", HttpStatus.BAD_REQUEST),
    ORDER_NOT_COMPLETED(7018, "Only COMPLETED orders can be returned", HttpStatus.BAD_REQUEST),
    ORDER_NOT_OWNED(7019, "You do not own this order", HttpStatus.FORBIDDEN),
    RETURN_PERIOD_EXPIRED(7020, "Return period (30 days) has expired", HttpStatus.BAD_REQUEST),
    DUPLICATE_RETURN_REQUEST(7021, "An active return request already exists for this order", HttpStatus.BAD_REQUEST),
    INVALID_STATUS_TRANSITION(7022, "Invalid return request status transition", HttpStatus.BAD_REQUEST),
    ORDER_DETAIL_NOT_FOUND(7023, "Order detail not found", HttpStatus.NOT_FOUND),
    BANK_INFO_REQUIRED(7024, "Bank name, account number and account holder are required for BANK_TRANSFER", HttpStatus.BAD_REQUEST),
    BANK_INFO_MUST_BE_NULL(7025, "Bank information must be null for STRIPE_PAYMENT", HttpStatus.BAD_REQUEST),

    PET_NOT_EXISTED(8001, "Pet does not exist", HttpStatus.NOT_FOUND),
    CAGE_EXISTED(8002, "Cage has already existed", HttpStatus.BAD_REQUEST),
    CAGE_NOT_EXISTED(8003, "Cage does not exist", HttpStatus.NOT_FOUND),
    BLOG_EXISTED(8004, "Blog has already existed", HttpStatus.BAD_REQUEST),
    BLOG_NOT_EXISTED(8005, "Blog does not exist", HttpStatus.NOT_FOUND),

    CATALOG_NOT_FOUND(9001, "Service catalog not found", HttpStatus.NOT_FOUND),
    USER_NOT_STAFF(9002, "User is not staff", HttpStatus.FORBIDDEN),
    INVALID_WORKING_TIME(9003, "Working time is invalid", HttpStatus.BAD_REQUEST),
    STAFF_SCHEDULE_NOT_EXISTED(9004, "Staff schedule not found", HttpStatus.NOT_FOUND),
    CANNOT_UPDATE(9005, "Cannot update schedule started", HttpStatus.BAD_REQUEST),
    SAME_STAFF(9006, "Same staff already exists", HttpStatus.BAD_REQUEST),
    SCHEDULE_ALREADY_EXISTS(9007, "Staff already has a schedule in this time range", HttpStatus.BAD_REQUEST),
    INVALID_DATE_RANGE(9008, "Date range is invalid", HttpStatus.BAD_REQUEST),
    STAFF_ALREADY_ASSIGNED_TO_SCHEDULE(9009, "Staff already assigned to this schedule", HttpStatus.BAD_REQUEST),
    WORK_SCHEDULE_NOT_EXISTED(9010, "Work schedule does not exist", HttpStatus.NOT_FOUND),
    WORK_SCHEDULE_EXISTED(9011, "Work schedule already exists", HttpStatus.BAD_REQUEST),
    STAFF_LIST_EMPTY(9012, "Staff list is empty", HttpStatus.BAD_REQUEST),
    CANNOT_CHECKIN(9013, "Cannot check in", HttpStatus.BAD_REQUEST),
    CANNOT_CHECKOUT(9014, "Cannot check out", HttpStatus.BAD_REQUEST),
    CATALOG_TIME_SLOT_NOT_FOUND(9015, "Catalog time slot not found", HttpStatus.NOT_FOUND),
    CATALOG_TIME_SLOT_EXISTED(9016, "Catalog time slot already exists", HttpStatus.BAD_REQUEST),
    BOOKING_NOT_FOUND(9017, "Booking not found", HttpStatus.NOT_FOUND),
    BOOKING_DETAIL_NOT_FOUND(9018, "Booking detail not found", HttpStatus.NOT_FOUND),
    INVALID_BOOKING_STATUS(9019, "Invalid booking status", HttpStatus.BAD_REQUEST),
    BOOKING_SLOT_UNAVAILABLE(9020, "Booking time slot is unavailable", HttpStatus.BAD_REQUEST),
    BOOKING_PAYMENT_EXPIRED(9021, "Booking payment deadline has expired", HttpStatus.BAD_REQUEST),
    STAFF_NOT_CHECKED_IN(9022, "Please check in before accepting booking", HttpStatus.BAD_REQUEST),
    STAFF_WORK_TIME_NOT_ENOUGH(9023, "Working shift does not have enough available time", HttpStatus.BAD_REQUEST),
    CANCEL_REASON_REQUIRED(9024, "Cancel reason is required", HttpStatus.BAD_REQUEST),
    PET_OWNER_INVALID(9025, "Pet does not belong to current user", HttpStatus.FORBIDDEN),
    BOOKING_TIME_INVALID(9026, "Booking time must be now or in the future", HttpStatus.BAD_REQUEST),
    ONLY_ONE_TIMESLOT_PER_BOOKING(9027, "Only one time slot is allowed per booking", HttpStatus.BAD_REQUEST),
    PET_ALREADY_BOOKED(9028, "Pet already has another active booking at this time", HttpStatus.CONFLICT),
    STAFF_OVERLAP_BOOKING(9029, "Staff already has another booking at this time", HttpStatus.CONFLICT),
    INVALID_BOOKING_TYPE(9030, "Booking type does not match the service location", HttpStatus.BAD_REQUEST),
    INVALID_PET_SPECIES(9031, "Pet species does not match the service", HttpStatus.BAD_REQUEST),
    PET_WEIGHT_REQUIRED(9032, "Pet weight is required for this service", HttpStatus.BAD_REQUEST),
    INVALID_PET_WEIGHT_RANGE(9033, "Pet weight range is not supported by this service", HttpStatus.BAD_REQUEST),

    WORK_SCHEDULE_IN_THE_PAST(9017, "Cannot create a work schedule in the past", HttpStatus.BAD_REQUEST),
    TOO_EARLY_TO_CHECKIN(9018, "It's not time to check in yet", HttpStatus.BAD_REQUEST),
    MISSED_CHECKIN(9019, "Check-in time has closed", HttpStatus.BAD_REQUEST),
    TOO_EARLY_TO_CHECKOUT(9020, "It's not time to check out yet", HttpStatus.BAD_REQUEST),
    ;

    int code;
    String message;
    HttpStatusCode httpStatusCode;

    ErrorCode(int code, String message, HttpStatusCode httpStatusCode) {
        this.code = code;
        this.message = message;
        this.httpStatusCode = httpStatusCode;
    }
}
